In [3]:
#include <iostream> // Para imprimir
#include <stdlib.h> // Malloc/free
#include <string>   // Jupyter no permite cosas tipo cout << 0.5 por cuestiones de tipo (<< esta definido
                    // tanto para strings como para numeros, cual deberia tomar? error!), asi que necesitamos castear cada cosa a string.
#include <cmath>    // math
using namespace std;

# Aritmetica Modular!

# Motivacion y Ejemplo

Imaginemos que tenemos el siguiente reloj que marca las `~9:10`:

<center>

![Reloj marcando las 9](./imgs/clock1.PNG)

</center>


Notemos que si adelantamos el reloj `4` horas obtenemos: `13:10`, o mejor dicho: `1:10`.

Si lo adelantamos `6` horas, pasamos a: `15:10`, o en realidad: `3:10`.

Si lo adelantamos `36` horas, pasamos a: `45:10`, o en realidad: `9:10` de vuelta!

En todos los ejemplos, no solamente hacemos la suma, sino que tenemos que reducir la respuesta
a un numero entre `1` y `12`.

Esto nos lleva a....


# Nuestro primer ejercicio!


Dar un algoritmo que dada una hora  (entera) $1 \leq h \leq 12$, y un tiempo de espera: $dt \geq 0$, determinar que hora sera despues de esperar $dt$ horas.


```
Input:
6
5

Output: 11

Input:
1
24

Output: 1
```


In [4]:
int adelanto_hora(int h, int dt){
    for(;dt > 0; dt--){
        h = h >= 12 ? h - 12 + 1 : h + 1;
    }

    return h;
}


In [5]:
cout << adelanto_hora(6,5) << endl;
cout << adelanto_hora(1,24) << endl;

11
1


In [6]:
int mejor_adelanto(int h, int dt){
    int n  = 0;
    int h_ = h + dt;
    int res = 0;
    while(true){
        res = h_ - 12 * n;
        if (res <= 12){
            return res;
        }
        n++;
    }
}

In [7]:
cout << mejor_adelanto(6,5) << endl;
cout << mejor_adelanto(1,24) << endl;

11
1


Fijemonos que lo que estamos haciendo es basicamente una division: 

```
25 |12
   |

25 |12
   |2

25 |12
24 |2

25 |12
 1 |2  <- cociente
 ↑
Resto
```

O Escrito en forma de ecuacion:

$$
25  = 12\cdot 2 + 1
$$


In [8]:
int GREAT_adelanto(int h,int dt){
    int h_      = h + dt;
    int divisor = h_/12;
    return h_ - 12*divisor;
}

In [9]:
cout << GREAT_adelanto(6,5) << endl;
cout << GREAT_adelanto(1,24) << endl;

11
1


Finisimo, Pero ahora que pasa si queremos expresar cambios tanto positivos (adelantos) como negativos (regresiones)?

In [10]:
cout << GREAT_adelanto(6,-7) << endl;
cout << GREAT_adelanto(6,-10) << endl;
cout << GREAT_adelanto(6,-12) << endl;

-1
-4
-6


No funciona :(, pero notemos que:

$$
\begin{align*}
12 - 1 &= 11 \\
12 - 4 &=  8 \\
12 - 6 &=  6 
\end{align*}
$$

In [11]:
int BEST_solution(int h, int dt){
    int h_ = h + dt;
    int modulo = h_ % 12;
    return modulo < 0 ? 12 + modulo : modulo;
}

In [12]:
int pmod(int a, int b){
    int modulo = a % b;
    return modulo < 0 ? b + modulo : modulo;
}

In [13]:
cout << BEST_solution(6,-5) << endl;
cout << BEST_solution(6,-6) << endl;
cout << BEST_solution(6,-7) << endl;
cout << BEST_solution(6,-10) << endl;
cout << BEST_solution(6,-12) << endl;

1
0
11
8
6


# Ejercicio: Recorridos en una matriz!


Dada una matriz cuadrada, imprimir: 

- La diagonal de la matriz
- La anti-diagonal de la matriz
- La diagonal de la matriz en orden inverso
- La anti-diagonal de la matriz en orden inverso

**Ejemplo:**

```

Input:

[1 2 3]
[4 5 6]
[7 8 9]

Output:

1 5 9
3 5 7
9 5 1
1 5 3


```



In [14]:
void print_diagonal(int** m, int n){
    for (int i = 0; i < n; i++)
        cout << m[i][i] << ' ';
    
    cout << endl;
}

In [15]:
void print_antidiagonal(int** m, int n){
    for (int i = 0; i < n; i++)
        cout << m[i][pmod(-(i+1),n)] << ' ';
    
    cout << endl;
}

In [16]:
void print_iantidiagonal(int** m, int n){
    for (int i = 0; i < n; i++)
        cout << m[pmod(-(i+1),n)][i] << ' ';
    
    cout << endl;
}

In [17]:
void print_idiagonal(int** m, int n){
    for (int i = 0; i < n; i++)
        cout << m[pmod(-(i+1),n)][pmod(-(i+1),n)] << ' ';
    
    cout << endl;
}

In [18]:
int** m;
int arr[3][3] = {{1,2,3},{4,5,6},{7,8,9}};
int* aux[3]   = {arr[0],arr[1],arr[2]};
m = &aux[0];
print_diagonal(m,3);
print_antidiagonal(m,3);
print_idiagonal(m,3);
print_iantidiagonal(m,3);


1 5 9 
3 5 7 
9 5 1 
7 5 3 


# Abstract away:


<center>

![meme1](./imgs/meme1.PNG)

</center>

Como se podran imaginar, este operador/truco es bastante util, basicamente cada vez que tengamos una estructura "circular" (que despues de tantas iteraciones vuelva al `0`), probablemente se termine usando el modulo, pero tambien tiene muchisimas otras utilidades!



# Ejercicio: is_even

Crear una funcion que imprima todos los elementos **pares** de un arreglo de enteros:


```
Input: [1,2,3,4,5]

Output: 2 4

Input: [1,3,5]

Output:

```

In [19]:
void print_even(int* xs, int n){
    for (int i = 0; i < n; i++){
        if (xs[i] % 2 == 0 )
            (cout << xs[i] << ' ');
    }
    cout << endl;
}

In [20]:
int* a;
int arr[4] = {1,2,3,4};
a = &arr[0];
print_even(a,4);

int arr2[3] = {1,3,5};
a = &arr2[0];
print_even(a,3);

2 4 



In [21]:
void print_multiple(int* xs, int n, int m){
    for (int i = 0; i < n; i++){
        if (xs[i] % m == 0 )
            (cout << xs[i] << ' ');
    }
    cout << endl;
}

# Ejercicio:

Un numero primo $p$ es un numero tal que:

- Sus unicos **divisores positivos** son `1` y el mismo.
- `p` **no** es `1`.

Dada una lista de numeros, imprimir solo los primos.

```
input: [1,2,3,4,5,6,7,8,9,10,11,12,13]
output:
2
3
5
7
11
13
```


In [22]:
bool is_prime(int n){
    for (int i = 2; i < n; i++){
        if (n % i == 0){
            return false;
        }
    }

    return n == 1 ? false : true;
}

In [23]:
void prime_printer(int* ns, int l){
    for (int i = 0; i < l; i++){
        if (is_prime(ns[i])){
            cout << ns[i] << endl;
        }
    }
}

In [24]:
int arr3[13] = {1,2,3,4,5,6,7,8,9,10,11,12,13};
a = &arr3[0];

prime_printer(a, 13);

2
3
5
7
11
13


# Ejercicio: Revertir los digitos!

Dado un numero entero no-negativo cualquiera: `n`, imprimir sus digitos en orden inverso:


```
Input: 3250

Output: 

0
5
2
3
```



In [25]:
void digit_printer(int n){
    if (n == 0){
        cout << 0 << endl;
        return;
    }

    while (n != 0){
        cout << n % 10 << endl;
        n = n / 10;
    }
}

In [26]:
digit_printer(3250);


0
5
2
3


Pero que pasa si en vez de imprimirlo, quisieramos el numero?

In [27]:
int digit_reverser(int n){
    int res = 0;
    while (n != 0){
        res = res * 10 + (n % 10);
        n = n / 10;
    }

    return res;
}

# Nais Ejercicio: Cifrado Cesar

El cifrado Cesar, nombrado por el emperador, fue un cifrado no solo razonablemente seguro durante su epoca, sino que tambien rapido, su funcionamiento se ilustra mejor por un ejemplo:


Dado un mensaje m:"Me gusta el quesito" y un desplazamiento d: 3, entonces se reemplaza cada letra por la d-esima letra que le sigue:

```
Me gusta el quesito!
Ph jxvwd ho txhvlwr!
```

Notemos que si una tuviesemos la letra 'Z' y el desplazamiento 1 entonces: 'Z' -> 'A', es decir, se devuelve al inicio.



In [28]:
cout << (int) 'A' << endl;
cout << (int) 'Z' << endl;
cout << (int) 'a' << endl;
cout << (int) 'z' << endl;



65
90
97
122


@0x7f8624e3cba0

In [29]:
int total_letras = (int) 'z' - (int) 'a';

In [30]:
bool es_minuscula(char c){
    int c_ = (int) c;
    return (int) 'a' <= c_ && c_ <= (int) 'z';
}

In [31]:
bool es_mayuscula(char c){
    int c_ = (int) c;
    return (int) 'A' <= c_ && c_ <= (int) 'Z';
}

In [32]:
char codificar_caracter(char c, int dt){
    if (es_minuscula(c)){
        return (char) (pmod((int) c - (int) 'a' + dt,total_letras) + (int) 'a');
    } else if (es_mayuscula(c))
    {
        return (char) (pmod((int) c - (int) 'A' + dt,total_letras) + (int) 'A');
    }

    return c;
}

In [33]:
void codificar_string(string* s, int dt){
    for (int i = 0; i < (*s).length(); i++){
        (*s)[i] = codificar_caracter((*s)[i],dt);
    }
}

In [34]:
string mensaje = "Me gusta el quesito!";
cout << mensaje << endl;
codificar_string(&mensaje,3);
cout << mensaje << endl;

Me gusta el quesito!
Ph jxvwd ho txhvlwr!


# PA LA CASA: Luhn's Algorithm

El algoritmo de luhn es usado para verificar la validez de cosas como: tarjetas de credito, numero de IMEI, Identificaciones, ....

Su funcionamiento es el siguiente: 

1.- Tome el numero original, y empezando desde el digito mas a la derecha, moviendose hacia la izquierda, duplique el valor de cada segundo digito (excluyendo el valor mas a la derecha).

2.- Reemplace el valor resultante en cada posicion con la suma de los digitos de la posicion.

3.- Sume los valores resultantes de todas las posiciones.

4.- Un numero es valido si esta suma es equivalente a `0` modulo `10`.


Ejemplo, si el numero es: `79927398713`.

Paso 1: 
``` 
         7  9  9  2  7  3  9  8  7  1 3
       * 1  2  1  2  1  2  1  2  1  2 1
         --------------------------------
         7  18 9  4  7  6  9 16  7  2 3
```

Paso 2:   
```
          7  18   9  4  7  6  9  16  7 2 3
       -> 7  1+8  9  4  7  6  9  1+6 7 2 3
       -> 7   9   9  4  7  6  9   7  7 2 3
```

Paso 3: 

`7 + 9 + 9 + 4 + 7 + 6 + 9 + 7 + 7 + 2 + 3 = 70`

Paso 4: 

```
70 `mod` 10 = 0, valido!
```

# Formalmente....

1) https://omegaup.com/arena/problem/Luhns-Algorithm/
2) https://omegaup.com/arena/problem/Plus1/

